### ISSUE TITLE
[Bug]: Dialog closing animation not working

### ISSUE THREAD

**Issue by prokhn** [radix-vue/radix-vue#458] opened 2023-10-20 13:54 UTC
### Environment

```bash
Developement/Production OS: Windows 11
Node version: 16.20.2
Package manager: yarn@3.6.4
Radix Vue version: 0.4.1
Vue version: 3.3.5
Client OS: Windows 11
Browser: Yandex	116.0.5845.888 (same as Chrome)
```

### Link to minimal reproduction

https://www.radix-vue.com/guides/animation.html

### Steps to reproduce

I just copied an example from [here](https://www.radix-vue.com/guides/animation.html) and changed classes to ones that I use
Open animation works perfectly, but there is no closing animation

I belive the same bug can be seen on main page on both Dialog and Alert Dialog components

### Describe the bug

No closing animation

### Expected behavior

It should be

**Comment by zernonia** [comment] 2023-10-20 14:41
@prokhn  can you provide a minimal reproduction please? 😁

**Comment by zernonia** [comment] 2023-10-20 15:50
Testing here and seems to be working https://stackblitz.com/edit/hfxgtx-kzw5xq?file=src%2FApp.vue

Please provide a minimal reproduction else I will be closing this

**Comment by prokhn** [comment] 2023-10-20 15:56
Very strange
I'll provide a minimal reproduction on Monday then

**Comment by prokhn** [comment] 2023-10-26 20:42
I'm really sorry for the late response, It was quite a hard week.

I found the problem - for some reason. I didn't have any close animation when I had this structure:

```html

<DialogPortal>
      <div class="...">
        <DialogOverlay class="..." />

        <DialogContent class="...">
```

I fixed it by moving DialogOverlay to level above:

```html

<DialogPortal>
      <DialogOverlay class="..." />

      <div class="...">
        <DialogContent class="...">
```

I tried to reproduce it on empty project, but it seems to be something wrong with CSS styles (or whatever) that I'm using with Radix-vue.

**Closed** 2023-10-26 20:43 UTC
Labels: bug, need-reproduction
