### ISSUE TITLE
[Feature]: Expose `selectedValue` / highlighted item in ComboboxRoot

### ISSUE THREAD

**Issue by HuakunShen** [radix-vue/radix-vue#986] opened 2024-06-02 07:51 UTC
### Describe the feature

https://github.com/radix-vue/radix-vue/blob/ac3a6da9efb9f7240c616665fb262a2447a991e2/packages/radix-vue/src/Combobox/ComboboxRoot.vue#L264

Can you expose the `selectedValue` with `v-model` or emit event?
![image](https://github.com/radix-vue/radix-vue/assets/33727687/24d70ec9-a259-4b03-aa82-1fa84a0a21a4)
I want to build something like this, where I can navigate through a list of items and display the details on the right.

I need to get the currently highlighted item but there doesn't seem to be an option.

### Additional information

- [ ] I intend to submit a PR for this feature.
- [ ] I have already implemented and/or tested this feature.

**Comment by zernonia** [comment] 2024-06-03 08:34
Seems like a duplicate of https://github.com/radix-vue/radix-vue/issues/744

**Closed** 2024-06-28 13:43 UTC
