### ISSUE TITLE
[Bug]: Dropdown Menu - clicking on trigger when modal `false` causing menu to close and reappear

### ISSUE THREAD

**Issue by rbertzg** [radix-vue/radix-vue#571] opened 2023-12-27 12:54 UTC
### Environment

```bash
Developement/Production OS: Windows 10 19043.1110
Node version: 16.0.0
Package manager: pnpm@8.6.0
Radix Vue version: 1.0.0
Vue version: 3.0.0
Nuxt version: 3.0.0
Nuxt mode: universal
Nuxt target: server
CSS framework: tailwindcss@3.3.3
Client OS: Windows 10 19043.1110
Browser: Chrome 90.0.4430.212
```

### Link to minimal reproduction

https://codesandbox.io/p/devbox/radix-vue-dropdownmenu-jr3jvj?file=%2Fsrc%2FApp.vue%3A42%2C27&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqnjsges0005356b32ub9ocw%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqnjsger0002356bs5ubnefg%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqnjsger0003356b67ydicwe%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqnjsger0004356but0k2ir1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqnjsger0002356bs5ubnefg%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqnjsger0001356b75yvdt6q%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqnju1nh006g356bxqcgw90f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A42%252C%2522startColumn%2522%253A27%252C%2522endLineNumber%2522%253A42%252C%2522endColumn%2522%253A27%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqnjsger0002356bs5ubnefg%2522%252C%2522activeTabId%2522%253A%2522clqnju1nh006g356bxqcgw90f%2522%257D%252C%2522clqnjsger0004356but0k2ir1%2522%253A%257B%2522id%2522%253A%2522clqnjsger0004356but0k2ir1%2522%252C%2522activeTabId%2522%253A%2522clqnjt9to003v356bo8mxjlcx%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clqnjt9to003v356bo8mxjlcx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clqnjsger0003356b67ydicwe%2522%253A%257B%2522id%2522%253A%2522clqnjsger0003356b67ydicwe%2522%252C%2522activeTabId%2522%253A%2522clqnjt7ms002v356bdyux47km%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clqnjt7ms002v356bdyux47km%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

Add :modal="false" to DropdownMenuRoot

### Describe the bug

When the dropdown menu is open, clicking the trigger immediately closes and reopens the menu. It happens only if  :modal="false" is added to DropdownMenuRoot

### Expected behavior

When dropdrown menu is open, clicking trigger shouldn't reopens the menu

**Comment by adirizky54** [comment] 2023-12-31 09:08
Same issue with me

**Comment by peter-emad99** [comment] 2023-12-31 11:14
same issue ,also i expect that clicking the trigger when menu is open it should close it

**Comment by zernonia** [comment] 2023-12-31 11:50
thanks guys! i will prioritize this next week 😁

**Closed** 2024-01-03 01:50 UTC
Labels: bug

**Comment by MellKam** [comment] 2024-01-05 15:24
It seems that after these changes, some functionality was broken, because now I can open more than one dropdown at a time. For some reason, they do not close when interacting outside. 
<img height="320px" src="https://github.com/radix-vue/radix-vue/assets/51422045/2a365b7e-a425-4f9f-91f9-07b900c05684" />

I propbably should open the issue, but I'm too lazy to create a reproduction in the sandbox right now

**Comment by peter-emad99** [comment] 2024-01-07 23:43
@MellKam  same issue happened with me

**Comment by zernonia** [comment] 2024-01-08 04:29
Thanks @MellKam  @peter-emad99 !
