### ISSUE TITLE
[Bug]: `SelectContent` is unnecessary wide for larger select options for position `item-aligned`

### ISSUE THREAD

**Issue by romansp** [radix-vue/radix-vue#566] opened 2023-12-18 21:14 UTC
### Environment

```bash
Developement/Production OS: macOS 14.2
Node version: 18.18.2
Radix Vue version: 1.2.4
Vue version: 3.3.11
CSS framework: tailwindcss@3.13.0
Browser: Edge 120.0.2210.61
```

### Link to minimal reproduction

https://stackblitz.com/edit/7ftmez?file=src%2FApp.vue

### Steps to reproduce

1. Go to [minimal repro link](https://stackblitz.com/edit/7ftmez?file=src%2FApp.vue)
2. Open `Select` when "Very very long name" option is selected. Notice how wide floating content is.
3. Choose another but shorter value, e.g. "One".
4. Open `Select`. This time content will be much narrower.

### Describe the bug

I noticed strange floating content width inconsistencies when using `Select` with various select values lengths. It stood out that sometimes `SelectContent` will appear way too wide than needed even considering that content should fully overlay `SelectTrigger`.

After some debugging I noticed that `SelectTrigger` briefly renders `SelectValue` twice and thus becomes twice as wide at the moment when `SelectContent` size and position is computed (see attached screenshots). 

I think it also results in computation error of content horizontal positioning. `clampedLeft` may be incorrect after trigger content becomes normal again.
https://github.com/radix-vue/radix-vue/blob/d8b4f1e3320bbf389a449ea15409a4a807b3c6cf/packages/radix-vue/src/Select/SelectItemAlignedPosition.vue#L73-L82

### Expected behavior

Content width should be more predictable and don't be unnecessary wide.

### Conext & Screenshots (if applicable)

![image](https://github.com/radix-vue/radix-vue/assets/3474842/4fff36e2-13a9-437c-a6c6-f48eba21b864)
![image](https://github.com/radix-vue/radix-vue/assets/3474842/9e7bc84d-26df-40f0-8370-8e644fd7067f)

**Comment by zernonia** [comment] 2024-01-10 03:40
Thanks @romansp . but I believe that is up to you how to style to component. Instead of `min-w-[160px]` you should probably update it to your preference width. 

It's not a bug from the Select component. Closing it yaa 😁

**Closed by zernonia** 2024-01-10 03:40 UTC
Labels: bug

**Comment by romansp** [comment] 2024-01-10 21:14
@zernonia I'm sorry about confusion and I think the issue still needs attention. `min-w-[160px]` class was just a copy paste from `SelectRoot` docs example and isn't relevant to the underlying issue. I have simplified stackblitz repro further. Can you please take another look to see if that makes sense?

### Steps to reproduce
1. Go to [minimal repro link](https://stackblitz.com/edit/7ftmez?file=src%2FApp.vue)
1. Switch between "Short value" and "Very very very long value" values.
1. Notice differences in popup width size. When "Very very very long value" is selected displayed popup is unnecessary wide, actually twice as wide as it's required to be.

`SelectItemAlignedPosition.vue` component pre-computes required `minWidth` just before popup is about to be displayed. 

And in that exact moment `SelectItemText` will be teleported twice. This is happening because both trees are mounted twice through `SelectContent`:

https://github.com/radix-vue/radix-vue/blob/e20324adfa40562107eec6f8682c7bbdc9ac83de/packages/radix-vue/src/Select/SelectContent.vue#L47-L61

Both `<Presence>` and `<Teleport>` are mounted briefly thus duplicating the total number of `<SelectItem>` instances.
